# Image Addition

In [8]:
import cv2
import numpy as np
x = np.uint8([250])
x

array([250], dtype=uint8)

In [9]:
y = np.uint8([10])
y

array([10], dtype=uint8)

In [13]:
cv2.add(x,y) # 250+10 = 260 => 255

array([[255]], dtype=uint8)

In [12]:
x+y # 250+10 = 260 % 256 = 4

array([4], dtype=uint8)

# Image Blending

In [21]:
img1 = cv2.imread('cap_0.jpg')
img2 = cv2.imread('cap_1.jpg')

dst = cv2.addWeighted(img1,0.7,img2,0.3,0)

cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Bitwise Operations

In [31]:
def showImage(img):
    cv2.imshow('image',img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [100]:
# Load two images
img1 = cv2.imread('sample.jpg')
img2 = cv2.imread('opencv-logo2.jpg')

In [101]:
# Resize logo image
rows,cols,channels = img2.shape
# showImage(img2)
img2 = cv2.resize(img2,(int(rows/2), int(cols/2)), interpolation=cv2.INTER_CUBIC)
# showImage(img2)

In [102]:
# I want to put logo on top-left corner, So I create a ROI
rows,cols,channels = img2.shape
roi = img1[0:rows, 0:cols ]
showImage(roi)

In [103]:
# Now create a mask of logo and create its inverse mask also
img2gray = cv2.cvtColor(img2,cv2.COLOR_BGR2GRAY)
showImage(img2gray)

In [104]:
# ret, mask = cv2.threshold(img2gray, 10, 255, cv2.THRESH_BINARY)
ret, mask = cv2.threshold(img2gray, 250, 255, cv2.THRESH_BINARY_INV)
showImage(mask)

In [ ]:
mask_inv = cv2.bitwise_not(mask)
showImage(mask_inv)

# Now black-out the area of logo in ROI
img1_bg = cv2.bitwise_and(roi,roi,mask = mask_inv)
showImage(img1_bg)

# Take only region of logo from logo image.
img2_fg = cv2.bitwise_and(img2,img2,mask = mask)
showImage(img2_fg)

# Put logo in ROI and modify the main image
dst = cv2.add(img1_bg,img2_fg)
showImage(dst)
img1[0:rows, 0:cols ] = dst

cv2.imshow('res',img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Reference
https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_core/py_image_arithmetics/py_image_arithmetics.html#image-arithmetics